# Generated by Django 3.1.4 on 2020-12-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digistash', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('money', models.IntegerField(default=999)),
                ('meat', models.IntegerField(default=999)),
                ('digimons', models.ManyToManyField(blank=True, null=True, to='digistash.Digimon')),
            ],
        ),
    ]
