# Generated by Django 3.1.4 on 2020-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digistash', '0002_auto_20201212_0239'),
        ('registration', '0002_remove_profile_digimons'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digimons',
            field=models.ManyToManyField(blank=True, to='digistash.Digimon'),
        ),
    ]
