# Generated by Django 3.1.4 on 2020-12-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_digimons'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='haveG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='haveT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='haveV',
            field=models.BooleanField(default=False),
        ),
    ]
