# Generated by Django 3.1.4 on 2020-12-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digistash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimon',
            name='Attacks',
            field=models.CharField(default='Some attack', max_length=200),
        ),
        migrations.AddField(
            model_name='digimon',
            name='attribute',
            field=models.CharField(choices=[('Vaccine', 'Vaccine'), ('Data', 'Data'), ('Virus', 'Virus'), ('Free', 'Free')], default=('Vaccine', 'Vaccine'), max_length=9),
        ),
        migrations.AddField(
            model_name='digimon',
            name='description',
            field=models.CharField(default='Some digimon', max_length=2000),
        ),
        migrations.AddField(
            model_name='digimon',
            name='level',
            field=models.CharField(choices=[('In-Training', 'In-Training'), ('Rookie', 'Rookie'), ('Champion', 'Champion'), ('Ultimate', 'Ultimate'), ('Mega', 'Mega')], default=('In-Training', 'In-Training'), max_length=11),
        ),
        migrations.AddField(
            model_name='digimon',
            name='type',
            field=models.CharField(choices=[('Baby Dragon', 'Baby dragon'), ('Dragon', 'Dragon'), ('Mythical Dragon', 'Mythical Dragon'), ('Holy Knight', 'Holy Knight'), ('Lesser', 'Lesser'), ('Reptile', 'Reptile'), ('Dark Dragon', 'Dark Dragon'), ('Cyborg', 'Cyborg'), ('Beast', 'Beast'), ('Insect', 'Insect'), ('Mammal', 'Mammal')], default=('Baby Dragon', 'Baby dragon'), max_length=16),
        ),
    ]
